version: '1.0'

services:
  product:
    image: tyordanovv/product-service:latest
    container_name: product-service
    ports:
      - "8083:8083"
    build: product-service
    mem_limit: 200m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - postgres

  delivery:
    image: tyordanovv/delivery-service:latest
    container_name: delivery-service
    ports:
      - "8080:8080"
    build: delivery-service
    mem_limit: 200m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - postgres

  email:
    image: tyordanovv/email-service:latest
    container_name: email-service
    ports:
      - "8081:8081"
    build: email-service
    mem_limit: 200m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring

  order:
    image: tyordanovv/erder-service:latest
    container_name: order-service
    ports:
      - "8082:8082"
    build: order-service
    mem_limit: 200m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

  mongodb:
    image: mongo:4.4.2
    mem_limit: 200m
    ports:
      - "27017:27017"
    command: mongod

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: