server.port: 8082

spring.application.name: order-service

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5432/order

server.error.include-message: always

logging:
  level:
    root: INFO
    bg.tyordanovv: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---
spring.config.active.on-profile: docker

server.port: 8082

app.eureka-server: eureka
