server.port: 8083
server.error.include-message: always

#logging:
#  level:
#    root: INFO
#    bg.tyordanovv: DEBUG
#client:
#  product:
#    url: http://localhost:8083
#spring:
#  application:
#    name: product
#  rabbitmq:
#    addresses: localhost:5672

---
spring.config.activate.on-profile: docker

server.port: 8080