server.port: 8083

spring.application.name: product-service

app.eureka-server: localhost

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

server.error.include-message: always

logging:
  level:
    root: INFO
    bg.tyordanovv: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---
spring.config.activate.on-profile: docker

app.eureka-server: eureka

server.port: 8080

spring.data.mongodb.host: mongodb
