server.port: 8083

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5432/product

server.error.include-message: always

logging:
  level:
    root: INFO
    bg.tyordanovv: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080